name: PoliteTeleports
main: jasonwynn10\PoliteTeleports\Main
src-namespace-prefix: jasonwynn10\PoliteTeleports
version: 1.0.0
api: 4.0.0
description: "A plugin which allows players to politely ask for a teleport"
author: "jasonwynn10"

permissions:
  PoliteTeleports.command.tpask:
    default: true
    description: "Allows the player to use /tpask"
  PoliteTeleports.command.tpaccept:
    default: true
    description: "Allows the player to use /tpaccept"
  PoliteTeleports.command.tpahere:
    default: true
    description: "Allows the player to use /tpahere"
  PoliteTeleports.command.tpconfig:
    default: true
    description: "Allows the player to use /tpconfig"
  PoliteTeleports.command.tpdeny:
    default: true
    description: "Allows the player to use /tpdeny"