Teleport Cooldown: 0 # seconds enforced between allowed teleports
Retry Interval: -1 # seconds between retrying to teleport after failure (-1 = never retry)

Defaults:
  Teleport Delay: 5 # seconds to wait before teleporting
  Teleport Countdown: true
  Alert Teleporting: true
  Alert Receiver: true