Teleport Cooldown: 0 # seconds enforced between allowed teleports
Retry Interval: -1 # seconds between retrying to teleport after failure (-1 = never retry)

Defaults:
  Teleport Delay: 5 # seconds to wait before teleporting
  Teleport Countdown: true # show an in-chat countdown to the player
  Alert Teleporting: true # send a message to the player when they teleport
  Alert Receiver: true # send a message to the target when a player teleports to them