Language: null # Plugin-specific language. Available languages: null, eng
Teleport Cooldown: 0 # seconds enforced between allowed teleports
Retry Interval: -1 # seconds between retrying to teleport after failure (-1 = never retry)
Stand Still: true # Deny player teleports if they walk away

Defaults:
  Teleport Delay: 5 # seconds to wait before teleporting
  Teleport Countdown: true # show an in-chat countdown to the player
  Alert Teleporting: true # send a message to the player when they teleport
  Alert Receiver: true # send a message to the target when a player teleports to them
  Random Location Radius: 10000 # radius in blocks to randomly teleport players within
  Random Location Safety: true # random teleport to safe locations only